Repository superhuntawesome/superpuzzawesome, pull requests merged in 2021-03, with the labels that each got.

#6 Setup CI for django
  .github/workflows/django.yml
  .pre-commit-config.yaml
  requirements.txt
Labels: chore

#7 Add deploy workflow and fix allowed hosts
  .github/release-drafter.yml
  .github/workflows/deploy.yml
  .github/workflows/django.yml
  .github/workflows/release-notes.yml
  README.md
  settings/base.py
  settings/prod.py
  settings/staging.py
Labels: chore

#8 Actually fix allowed hosts
  settings/prod.py
  settings/staging.py
Labels: fix

#9 ACTUALLY fix allowed hosts
  .github/workflows/django.yml
  README.md
  puzzlord/settings.py
  settings/base.py
Labels: fix

#10 Favicon and Change Homepage to say SuperPuzzAwesome
  puzzle_editing/static/favicon.ico
  puzzle_editing/templates/base.html
  puzzle_editing/templates/index.html
  puzzle_editing/templates/index_not_logged_in.html
Labels: enhancement

#12 Change top navbar to be a sidebar
  puzzle_editing/static/css/general.css
  puzzle_editing/static/mojo-spa.png
  puzzle_editing/templates/base.html
  puzzle_editing/templates/index_not_logged_in.html
  puzzle_editing/templates/login.html
  puzzle_editing/templates/new.html
  puzzle_editing/templates/puzzle.html
  puzzle_editing/templates/tags/nav_link.html
  puzzle_editing/templatetags/nav_link.py
Labels: enhancement

#13 Responsive menus
  puzzle_editing/static/css/general.css
  puzzle_editing/templates/base.html
Labels: enhancement

#15 Don't hardcode log file path
  settings/base.py
Labels: fix

#16 Update static files path for production
  settings/base.py
Labels: fix

#20 Streamline puzzle statuses
  puzzle_editing/graph.py
  puzzle_editing/status.py
  puzzle_editing/templates/base.html
  puzzle_editing/templates/factcheck.html
  puzzle_editing/templates/index.html
  puzzle_editing/templates/needs_editor.html
  puzzle_editing/templates/postprod.html
  puzzle_editing/templates/tags/puzzle_list.html
  puzzle_editing/templatetags/puzzle_list.py
  puzzle_editing/tests.py
  puzzle_editing/urls.py
  puzzle_editing/views.py
Labels: enhancement

#18 Forget Password flow
  README.md
  puzzle_editing/templates/login.html
  puzzle_editing/templates/reset_password.html
  puzzle_editing/templates/reset_password_complete.html
  puzzle_editing/templates/reset_password_confirm.html
  puzzle_editing/templates/reset_password_done.html
  puzzle_editing/urls.py
Labels: enhancement
